import os
import json
import random
import requests
import datetime

# --- CONFIGURATION ---
VIDEO_FOLDER = "videos"
HISTORY_FILE = "history.json"
TELEGRAM_BOT_TOKEN = os.environ.get("TELEGRAM_TOKEN")
TELEGRAM_CHAT_ID = os.environ.get("TELEGRAM_CHAT_ID")
WEBHOOK_URL = os.environ.get("WEBHOOK_URL")

# Yahan maine image se dekh kar aapka exact Repo Name daal diya hai
GITHUB_REPO = "Automation8248/offernix-page-" 
BRANCH_NAME = "main"

# --- DATA GRID (Pre-saved Titles & Captions) ---

# List 1: Titles (Har bar inme se koi ek randomly select hoga)
TITLES_GRID = [
    "Most Viral Gadget of 2026 😱",
    "You Need This Product Now!",
    "Best Amazon Find Today 🔥",
    "This Will Change Your Life",
    "Smartest Gadget I Found Online",
    "Don't Miss This Deal!",
    "Top Rated Product Review",
    "Why Everyone is Buying This?",
    "Coolest Tech Under $50",
    "Must Have Home Gadget",
    "Unbelievable Useful Tool",
    "Stop Scrolling and Watch This!",
    "The Ultimate Problem Solver",
    "Best Gift Idea for 2026",
    "Hidden Gem Product Found 💎"
    "This Made My Life Easier",
    "I Didn’t Know I Needed This",
    "Why Is Everyone Buying This?",
    "This Is Actually Useful",
    "I Finally Tried This",
    "Small Thing Big Difference",
    "This Just Makes Sense",
    "I Get The Hype Now",
    "I Wasn’t Expecting This",
    "This Solves A Daily Problem",
    "I Use This Every Day Now",
    "This Is Surprisingly Good",
    "People Keep Recommending This",
    "I Wish I Found This Earlier",
    "This Is Pretty Clever",
    "This Made Things Faster",
    "I Didn’t Think It Would Work",
    "This Is Quietly Helpful",
    "This Became A Habit",
    "I Was Skeptical At First",
    "This Feels Premium",
    "This Is So Practical",
    "Now I Understand",
    "I Keep Reaching For This",
    "This Fixed A Small Annoyance",
    "Simple But Smart",
    "This Is Worth It",
    "I Didn’t Expect Quality",
    "This Is A Smart Buy",
    "This Helps More Than Expected",
    "Better Than I Thought",
    "This Just Works",
    "This Made Daily Tasks Easy",
    "I Didn’t Notice Until I Used It",
    "This Is Actually Convenient",
    "I Keep Using This",
    "This Is A Clever Idea",
    "I Regret Not Buying Sooner",
    "This Is Comfort Upgrade",
    "This Is Quietly Popular",
    "I Didn’t Expect Daily Use",
    "This Is Handy",
    "This Is Very Practical",
    "I Finally Get It",
    "This Makes Routine Better",
    "This Is A Nice Upgrade",
    "I Didn’t Expect To Like It",
    "This Helps A Lot",
    "This Is Smart Design",
    "This Is Useful Everywhere",
    "I Was Wrong About This",
    "This Made My Routine Faster",
    "This Feels Well Made",
    "I Like This More Than Expected",
    "This Is A Good Idea",
    "I Use It All The Time",
    "This Is Reliable",
    "I Didn’t Expect This Much",
    "This Is A Hidden Gem",
    "This Makes Things Simple",
    "I Didn’t Expect Convenience",
    "This Is Helpful Daily",
    "This Is Easy To Use",
    "This Feels Thoughtful",
    "This Became Essential",
    "This Is Worth Having",
    "This Made My Life Easier",
    "I Didn’t Know I Needed This",
    "Why Is Everyone Buying This?",
    "This Is Actually Useful",
    "I Finally Tried This",
    "Small Thing Big Difference",
    "This Just Makes Sense",
    "I Get The Hype Now",
    "I Wasn’t Expecting This",
    "This Solves A Daily Problem",
    "I Use This Every Day Now",
    "This Is Surprisingly Good",
    "People Keep Recommending This",
    "I Wish I Found This Earlier",
    "This Is Pretty Clever",
    "This Made Things Faster",
    "I Didn’t Think It Would Work",
    "This Is Quietly Helpful",
    "This Became A Habit",
    "I Was Skeptical At First",
    "This Feels Premium",
    "This Is So Practical",
    "Now I Understand",
    "I Keep Reaching For This",
    "This Fixed A Small Annoyance",
    "Simple But Smart",
    "This Is Worth It",
    "I Didn’t Expect Quality",
    "This Is A Smart Buy",
    "This Helps More Than Expected",
    "Better Than I Thought",
    "This Just Works",
    "This Made Daily Tasks Easy",
    "I Didn’t Notice Until I Used It",
    "This Is Actually Convenient",
    "I Keep Using This",
    "This Is A Clever Idea",
    "I Regret Not Buying Sooner",
    "This Is Comfort Upgrade",
    "This Is Quietly Popular",
    "I Didn’t Expect Daily Use",
    "This Is Handy",
    "This Is Very Practical",
    "I Finally Get It",
    "This Makes Routine Better",
    "This Is A Nice Upgrade",
    "I Didn’t Expect To Like It",
    "This Helps A Lot",
    "This Is Smart Design",
    "This Is Useful Everywhere",
    "I Was Wrong About This",
    "This Made My Routine Faster",
    "This Feels Well Made",
    "I Like This More Than Expected",
    "This Is A Good Idea",
    "I Use It All The Time",
    "This Is Reliable",
    "I Didn’t Expect This Much",
    "This Is A Hidden Gem",
    "This Makes Things Simple",
    "I Didn’t Expect Convenience",
    "This Is Helpful Daily",
    "This Is Easy To Use",
    "This Feels Thoughtful",
    "This Became Essential",
    "This Is Worth Having",
    "I Didn’t Think About This Before",
    "This Is Pretty Nice",
    "This Solves A Tiny Problem",
    "This Works Smoothly",
    "I Didn’t Expect This Comfort",
    "This Is Subtle But Good",
    "I Keep It Nearby",
    "This Is A Useful Upgrade",
    "This Is Clean And Simple",
    "I Use This More Than Anything",
    "This Is Practical Living",
    "I Didn’t Expect This Benefit",
    "This Makes Life Better",
    "This Is A Small Luxury",
    "I Didn’t Expect To Care",
    "This Is Well Designed",
    "This Helps Organize Things",
    "This Is Convenient",
    "I Didn’t Expect This Ease",
    "This Is Everyday Helpful",
    "This Is Low Effort",
    "This Helps Daily Routine",
    "I Didn’t Expect To Recommend",
    "This Is Worth Trying",
    "This Makes Things Better",
    "I Didn’t Expect Reliability",
    "This Is Comfortable",
    "This Is Easy Living",
    "I Didn’t Expect To Depend",
    "This Is Good Value",
    "This Helps Save Time",
    "I Didn’t Expect Smoothness",
    "This Is Nice To Have",
    "I Didn’t Expect Improvement",
    "This Is Handy Tool",
    "This Is Simple Comfort",
    "I Didn’t Expect Habit",
    "This Helps Quickly",
    "This Is A Solid Pick",
    "I Didn’t Expect This Result",
    "This Is A Quiet Upgrade",
    "I Didn’t Expect To Keep Using",
    "This Is Useful Anywhere",
    "I Didn’t Expect This Feature",
    "This Is Practical Choice",
    "I Didn’t Expect Difference",
    "This Is Everyday Convenience",
    "I Didn’t Expect To Notice",
    "This Is Helpful Around Home",
    "I Didn’t Expect To Enjoy",
    "This Is Comfortable To Use",
    "I Didn’t Expect Simplicity",
    "This Is A Good Addition",
    "I Didn’t Expect Daily Benefit",
    "This Is A Small Fix",
    "I Didn’t Expect Long Use",
    "This Is Reliable Helper",
    "I Didn’t Expect To Like Daily",
    "This Is Clean Upgrade",
    "I Didn’t Expect Easy Setup",
    "This Is Useful Pick",
    "I Didn’t Expect Smartness",
    "This Is Good For Everyone",
    "I Didn’t Expect Smooth Routine",
    "This Is Daily Essential",
    "I Didn’t Expect Worth",
    "This Is Quiet Improvement",
    "I Didn’t Expect Fast Use",
    "This Is Helpful Design",
    "I Didn’t Expect Comfort Daily",
    "This Is Handy Item",
    "I Didn’t Expect Organization",
    "This Is Practical Helper",
    "I Didn’t Expect To Appreciate",
    "This Is Better Living",
    "I Didn’t Expect Ease Daily",
    "This Is Useful Comfort",
    "I Didn’t Expect Routine Change",
    "This Is Smart Upgrade",
    "I Didn’t Expect Convenience Daily",
    "This Is Functional",
    "I Didn’t Expect To Need",
    "This Is Worth Keeping",
    "I Didn’t Expect This Much Help",
    "This Is Organized Living",
    "I Didn’t Expect Better Routine",
    "This Is Clean Living",
    "I Didn’t Expect Daily Habit",
    "This Is A Good Upgrade",
    "I Didn’t Expect Smooth Use",
    "This Is Easy Helper",
    "I Didn’t Expect Practical Joy",
    "This Is Comfortable Living",
    "I Didn’t Expect Subtle Change",
    "This Is Nice Improvement",
    "I Didn’t Expect To Miss It",
    "This Is Helpful Support",
    "I Didn’t Expect Life Easier",
    "This Is Useful Solution",
    "I Didn’t Expect Everyday Use",
    "This Is Calm Upgrade",
    "I Didn’t Expect To Use Often",
    "This Is A Simple Fix",
    "I Didn’t Expect Fast Help",
    "This Is Efficient",
    "I Didn’t Expect Daily Comfort",
    "This Is Reliable Choice",
    "I Didn’t Expect To Share",
    "This Is Smart Everyday Tool",
    "I Didn’t Expect It Matters",
    "This Is Convenient Tool",
    "I Didn’t Expect This Level",
    "This Is Good For Routine",
    "I Didn’t Expect Small Luxury",
    "This Is Worth Daily Use",
    "I Didn’t Expect Smooth Life",
    "This Is Comfortable Choice",
    "I Didn’t Expect To Keep",
    "This Is Practical Upgrade",
    "I Didn’t Expect Instant Benefit",
    "This Is Everyday Tool",
    "I Didn’t Expect Better Flow",
    "This Is A Nice Helper",
    "I Didn’t Expect Easy Living",
    "This Is Organized Comfort",
    "I Didn’t Expect Helpful Daily",
    "This Is Reliable Tool",
    "I Didn’t Expect Routine Ease",
    "This Is Smart Comfort",
    "I Didn’t Expect Consistent Use",
    "This Is Worth Owning",
    "I Didn’t Expect Simple Joy",
    "This Is Helpful Upgrade",
    "I Didn’t Expect Daily Value",
    "This Is Small But Good",
    "I Didn’t Expect Smooth Day",
    "This Is Good Habit Tool",
    "I Didn’t Expect Quick Help",
    "This Is Helpful Pick",
    "I Didn’t Expect Calm Routine",
    "This Is Clean Design",
    "I Didn’t Expect To Prefer",
    "This Is Smart Living",
    "I Didn’t Expect Comfort Upgrade",
    "This Is Useful Everyday",
    "I Didn’t Expect Better Organization",
    "This Is A Solid Upgrade",
    "I Didn’t Expect Daily Need",
    "This Is Good Routine Tool",
    "I Didn’t Expect Convenience Boost",
    "This Is Practical Living Tool",
    "I Didn’t Expect Fast Routine",
    "This Is Helpful Daily Item",
    "I Didn’t Expect Small Upgrade",
    "This Is Worth Daily Use",
    "I Didn’t Expect Clean Setup",
    "This Is Reliable Everyday Tool",
    "I Didn’t Expect Comfort Fix",
    "This Is A Good Helper",
    "I Didn’t Expect Quick Routine",
    "This Is Smart Daily Pick",
    "I Didn’t Expect To Keep Nearby",
    "This Is A Quiet Helper",
    "I Didn’t Expect Daily Relief",
    "This Is Everyday Comfort",
    "I Didn’t Expect Smooth Tasks",
    "I Didn’t Think About This Before",
    "This Is Pretty Nice",
    "This Solves A Tiny Problem",
    "This Works Smoothly",
    "I Didn’t Expect This Comfort",
    "This Is Subtle But Good",
    "I Keep It Nearby",
    "This Is A Useful Upgrade",
    "This Is Clean And Simple",
    "I Use This More Than Anything",
    "This Is Practical Living",
    "I Didn’t Expect This Benefit",
    "This Makes Life Better",
    "This Is A Small Luxury",
    "I Didn’t Expect To Care",
    "This Is Well Designed",
    "This Helps Organize Things",
    "This Is Convenient",
    "I Didn’t Expect This Ease",
    "This Is Everyday Helpful",
    "This Is Low Effort",
    "This Helps Daily Routine",
    "I Didn’t Expect To Recommend",
    "This Is Worth Trying",
    "This Makes Things Better",
    "I Didn’t Expect Reliability",
    "This Is Comfortable",
    "This Is Easy Living",
    "I Didn’t Expect To Depend",
    "This Is Good Value",
    "This Helps Save Time",
    "I Didn’t Expect Smoothness",
    "This Is Nice To Have",
    "I Didn’t Expect Improvement",
    "This Is Handy Tool",
    "This Is Simple Comfort",
    "I Didn’t Expect Habit",
    "This Helps Quickly",
    "This Is A Solid Pick",
    "I Didn’t Expect This Result",
    "This Is A Quiet Upgrade",
    "I Didn’t Expect To Keep Using",
    "This Is Useful Anywhere",
    "I Didn’t Expect This Feature",
    "This Is Practical Choice",
    "I Didn’t Expect Difference",
    "This Is Everyday Convenience",
    "I Didn’t Expect To Notice",
    "This Is Helpful Around Home",
    "I Didn’t Expect To Enjoy",
    "This Is Comfortable To Use",
    "I Didn’t Expect Simplicity",
    "This Is A Good Addition",
    "I Didn’t Expect Daily Benefit",
    "This Is A Small Fix",
    "I Didn’t Expect Long Use",
    "This Is Reliable Helper",
    "I Didn’t Expect To Like Daily",
    "This Is Clean Upgrade",
    "I Didn’t Expect Easy Setup",
    "This Is Useful Pick",
    "I Didn’t Expect Smartness",
    "This Is Good For Everyone",
    "I Didn’t Expect Smooth Routine",
    "This Is Daily Essential",
    "I Didn’t Expect Worth",
    "This Is Quiet Improvement",
    "I Didn’t Expect Fast Use",
    "This Is Helpful Design",
    "I Didn’t Expect Comfort Daily",
    "This Is Handy Item",
    "I Didn’t Expect Organization",
    "This Is Practical Helper",
    "I Didn’t Expect To Appreciate",
    "This Is Better Living",
    "I Didn’t Expect Ease Daily",
    "This Is Useful Comfort",
    "I Didn’t Expect Routine Change",
    "This Is Smart Upgrade",
    "I Didn’t Expect Convenience Daily",
    "This Is Functional",
    "I Didn’t Expect To Need",
    "This Is Worth Keeping",
    "I Didn’t Expect This Much Help",
    "This Is Organized Living",
    "I Didn’t Expect Better Routine",
    "This Is Clean Living",
    "I Didn’t Expect Daily Habit",
    "This Is A Good Upgrade",
    "I Didn’t Expect Smooth Use",
    "This Is Easy Helper",
    "I Didn’t Expect Practical Joy",
    "This Is Comfortable Living",
    "I Didn’t Expect Subtle Change",
    "This Is Nice Improvement",
    "I Didn’t Expect To Miss It",
    "This Is Helpful Support",
    "I Didn’t Expect Life Easier",
    "This Is Useful Solution",
    "I Didn’t Expect Everyday Use",
    "This Is Calm Upgrade",
    "I Didn’t Expect To Use Often",
    "This Is A Simple Fix",
    "I Didn’t Expect Fast Help",
    "This Is Efficient",
    "I Didn’t Expect Daily Comfort",
    "This Is Reliable Choice",
    "I Didn’t Expect To Share",
    "This Is Smart Everyday Tool",
    "I Didn’t Expect It Matters",
    "This Is Convenient Tool",
    "I Didn’t Expect This Level",
    "This Is Good For Routine",
    "I Didn’t Expect Small Luxury",
    "This Is Worth Daily Use",
    "I Didn’t Expect Smooth Life",
    "This Is Comfortable Choice",
    "I Didn’t Expect To Keep",
    "This Is Practical Upgrade",
    "I Didn’t Expect Instant Benefit",
    "This Is Everyday Tool",
    "I Didn’t Expect Better Flow",
    "This Is A Nice Helper",
    "I Didn’t Expect Easy Living",
    "This Is Organized Comfort",
    "I Didn’t Expect Helpful Daily",
    "This Is Reliable Tool",
    "I Didn’t Expect Routine Ease",
    "This Is Smart Comfort",
    "I Didn’t Expect Consistent Use",
    "This Is Worth Owning",
    "I Didn’t Expect Simple Joy",
    "This Is Helpful Upgrade",
    "I Didn’t Expect Daily Value",
    "This Is Small But Good",
    "I Didn’t Expect Smooth Day",
    "This Is Good Habit Tool",
    "I Didn’t Expect Quick Help",
    "This Is Helpful Pick",
    "I Didn’t Expect Calm Routine",
    "This Is Clean Design",
    "I Didn’t Expect To Prefer",
    "This Is Smart Living",
    "I Didn’t Expect Comfort Upgrade",
    "This Is Useful Everyday",
    "I Didn’t Expect Better Organization",
    "This Is A Solid Upgrade",
    "I Didn’t Expect Daily Need",
    "This Is Good Routine Tool",
    "I Didn’t Expect Convenience Boost",
    "This Is Practical Living Tool",
    "I Didn’t Expect Fast Routine",
    "This Is Helpful Daily Item",
    "I Didn’t Expect Small Upgrade",
    "This Is Worth Daily Use",
    "I Didn’t Expect Clean Setup",
    "This Is Reliable Everyday Tool",
    "I Didn’t Expect Comfort Fix",
    "This Is A Good Helper",
    "I Didn’t Expect Quick Routine",
    "This Is Smart Daily Pick",
    "I Didn’t Expect To Keep Nearby",
    "This Is A Quiet Helper",
    "I Didn’t Expect Daily Relief",
    "This Is Everyday Comfort",
    "I Didn’t Expect Smooth Tasks",
    "This Is A Handy Upgrade",
    "I Didn’t Expect Better Comfort",
    "This Is A Useful Habit",
    "I Didn’t Expect Organized Routine",
    "This Is Worth Having Around",
    "I Didn’t Expect Daily Ease",
    "This Is Practical Comfort",
    "I Didn’t Expect Helpful Tool",
    "This Is A Clean Upgrade",
    "I Didn’t Expect Simple Help",
    "This Is Comfortable Routine",
    "I Didn’t Expect Useful Everyday",
    "This Is A Nice Tool",
    "I Didn’t Expect Easy Comfort",
    "This Is Helpful Living Tool",
    "I Didn’t Expect Small Change",
    "This Is Reliable Daily Helper",
    "I Didn’t Expect To Enjoy Using",
    "This Is Smart Everyday Helper",
    "I Didn’t Expect Smooth Experience",
    "This Is Good Lifestyle Upgrade",
    "I Didn’t Expect Useful Comfort",
    "This Is Everyday Support",
    "I Didn’t Expect Helpful Routine",
    "This Is A Comfortable Pick",
    "I Didn’t Expect Better Habit",
    "This Is A Simple Upgrade",
    "I Didn’t Expect Daily Smoothness",
    "This Is Useful Support",
    "I Didn’t Expect Easy Tasks",
    "This Is A Reliable Pick",
    "I Didn’t Expect Daily Simplicity",
    "This Is A Smart Addition",
    "I Didn’t Expect Helpful Comfort",
    "This Is Worth Daily Routine",
    "I Didn’t Expect Consistent Help",
    "This Is A Practical Pick",
    "I Didn’t Expect Calm Living",
    "This Is Comfortable Helper",
    "I Didn’t Expect Useful Habit",
    "This Is A Helpful Choice",
    "I Didn’t Expect Organized Living",
    "This Is Smart Practical Living"
]


# List 2: Captions (Har bar inme se koi ek randomly select hoga)
CAPTIONS_GRID = [
    "I found this online and didn’t expect it to actually make my daily routine this much easier.",
    "This simple product solved a small daily problem that used to waste my time every day.",
    "If you like practical gadgets that save effort and time, this one is worth checking out.",
    "Not an ad just sharing something useful that I’ve been using almost every single day.",
    "Sometimes small upgrades create big comfort and this product proves exactly that.",
    "Budget friendly but feels premium in hand and works exactly like described online.",
    "I tried it out of curiosity and now it has become part of my everyday routine.",
    "Perfect for people who love smart and simple solutions instead of complicated tools.",
    "People online kept recommending this and now I understand why it’s trending everywhere.",
    "Helps reduce effort in daily tasks and honestly saves more time than expected.",
    "If you enjoy practical lifestyle upgrades this is a really satisfying purchase option.",
    "Didn’t think I needed it but after using it once I kept using it every day.",
    "This product is simple useful and surprisingly effective for regular daily use.",
    "One of those rare finds that are affordable yet genuinely helpful in daily life.",
    "Works smoothly without extra setup and that’s exactly what makes it convenient.",
    "Bought it randomly and ended up recommending it to friends and family.",
    "A small investment that actually improves comfort and daily productivity.",
    "Useful at home useful outside and works consistently without hassle.",
    "If convenience matters to you this is definitely worth a quick look.",
    "Smart design combined with practical usage makes this a daily essential.",
    "Great option for anyone trying to simplify their daily routine easily.",
    "This kind of product quietly improves life without you even noticing.",
    "Simple solution for a common problem most people deal with daily.",
    "Not flashy but extremely practical and that’s why people like it.",
    "Feels like something that should have existed much earlier honestly.",
    "Helpful for busy schedules where saving time really matters.",
    "Lightweight easy to use and does exactly what it promises online.",
    "After a week of use I realized how often I actually needed this.",
    "Affordable upgrade that adds comfort without overcomplicating things.",
    "If you like useful items instead of decorative ones this fits perfectly.",
    "Great balance between price quality and everyday usefulness.",
    "Minimal effort required and results are noticeable instantly.",
    "Many people are switching to this because it simply makes sense.",
    "I appreciate products that are simple yet thoughtfully designed like this.",
    "Convenience products like this make daily life smoother naturally.",
    "Not trending for no reason it’s genuinely practical and helpful.",
    "Easy to carry easy to use and easy to recommend honestly.",
    "Perfect addition for organized and efficient daily living.",
    "I like how it reduces small frustrations throughout the day.",
    "Sometimes functionality matters more than looks and this proves it.",
    "A simple upgrade that improves workflow without learning anything new.",
    "Useful for students workers and basically anyone with a routine.",
    "This saved me small bits of time repeatedly during the day.",
    "Smart lifestyle products like this are worth trying once.",
    "I rarely recommend products but this one deserves a mention.",
    "Works quietly in the background and keeps things easier.",
    "One of the more practical online purchases I’ve made recently.",
    "After testing many similar items this one felt the most reliable.",
    "Good option if you prefer useful purchases instead of impulse buys.",
    "Daily convenience matters more than luxury and this helps with that.",
    "Compact size but noticeable difference in everyday tasks.",
    "Great little helper that supports productivity naturally.",
    "Even non tech people can use it without confusion.",
    "Designed for real life usage rather than just appearance.",
    "Something you don’t think about until you actually use it.",
    "I appreciate tools that remove effort instead of adding steps.",
    "Helps maintain a smoother and more organized routine.",
    "A practical product that works consistently without maintenance.",
    "Small comfort improvements add up over time and this helps.",
    "One of those items you end up using more than expected.",
    "Better than many alternatives I tried before online.",
    "Easy solution instead of temporary workarounds daily.",
    "Useful in multiple situations which increases its value.",
    "Helpful purchase for improving daily efficiency naturally.",
    "Clean design with clear purpose and simple usability.",
    "If practicality had a form this product would be it.",
    "Great choice for minimalists who value functionality.",
    "Works well for long term use instead of one time use.",
    "Nice option for gifting because almost anyone can use it.",
    "Convenience tools like this reduce unnecessary effort daily.",
    "Helps you focus on work instead of small repetitive tasks.",
    "Perfect example of smart design solving everyday problems.",
    "Reliable performance without complicated instructions.",
    "Useful whether you work from home or outside daily.",
    "A small change that positively affects routine comfort.",
    "Actually performs like the product page described.",
    "I now understand why people kept recommending it online.",
    "Helpful addition to a modern and efficient lifestyle.",
    "Works in seconds and requires almost zero learning.",
    "Simple solution that removes repeated frustration.",
    "Feels satisfying every time you use it honestly.",
    "Practical upgrade that quickly becomes a habit.",
    "One purchase that keeps giving value over time.",
    "Great usability compared to similar price products.",
    "Made daily work slightly easier which matters a lot.",
    "Convenience is underrated until you experience it.",
    "Helpful for maintaining productivity during busy days.",
    "Something everyone can benefit from using regularly.",
    "Reduces effort without changing your routine.",
    "Reliable tool that just works when needed.",
    "Practical idea implemented in a simple way.",
    "Perfect for everyday comfort improvement.",
    "Functional product that earns its place quickly.",
    "Smart purchase for long term daily use.",
    "Useful in both home and travel situations.",
    "Helps keep routine smoother consistently.",
    "Comfort focused design that feels natural.",
    "Good quality feel considering the price.",
    "Easy improvement instead of replacement.",
    "Helpful modern lifestyle addition.",
    "Works the way a good product should.",
    "Practical enough to recommend confidently.",
    "Small but meaningful life upgrade.",
    "Simple helpful daily companion.",
    "Effortless usability makes it enjoyable.",
    "Helps reduce repetitive effort daily.",
    "Great value for practical use.",
    "Consistent performance matters and this delivers.",
    "Smart simple everyday essential.",
    "Nice combination of comfort and function.",
    "Works reliably across situations.",
    "Convenient and straightforward solution."
]


# List 3: Fixed Hashtags (Ye har video me SAME rahega)
FIXED_HASHTAGS = """
.
.
.
.
.
#AffiliateMarketing #OnlineEarning #PassiveIncome #MakeMoneyOnline #EarnOnline #DigitalMarketing #InternetMarketing #SideIncome #SmartIncome #ProductReview #ProductVideo #BestProduct #TrendingProduct #TopDeals #MustBuy #UnboxingVideo #ProductDemo #HonestReview #WorthBuying #BuyNow #BestDeal #DiscountOffer #LimitedOffer #OfferAlert #SaleAlert #DealOfTheDay #OnlineShopping #BestPrice #ReelsIndia #InstaReels #ViralReels #TrendingReels #ExplorePage #YoutubeShorts #ShortsVideo #ViralVideo #IndianAffiliate #IndiaDeals #IndianProducts #DesiDeals"""

# Isse AFFILIATE_HASHTAGS se badal kar INSTA_HASHTAGS kar diya hai
INSTA_HASHTAGS = """
.
.
.
.
"#Affiliate #BestDeals #SmartGadgets #TopProduct #Shopping"


# --- HELPER FUNCTIONS ---

def load_history():
    if not os.path.exists(HISTORY_FILE):
        return []
    with open(HISTORY_FILE, 'r') as f:
        return json.load(f)

def save_history(data):
    with open(HISTORY_FILE, 'w') as f:
        json.dump(data, f, indent=4)

# --- MAIN LOGIC ---

def run_automation():
    # 1. DELETE OLD FILES (15 Days Logic)
    history = load_history()
    today = datetime.date.today()
    new_history = []
    
    print("Checking for expired videos...")
    for entry in history:
        sent_date = datetime.date.fromisoformat(entry['date_sent'])
        days_diff = (today - sent_date).days
        
        file_path = os.path.join(VIDEO_FOLDER, entry['filename'])
        
        if days_diff >= 15:
            if os.path.exists(file_path):
                os.remove(file_path)
                print(f"DELETED EXPIRED: {entry['filename']}")
        else:
            new_history.append(entry)
    
    save_history(new_history)
    history = new_history 

    # 2. PICK NEW VIDEO
    if not os.path.exists(VIDEO_FOLDER):
        os.makedirs(VIDEO_FOLDER)
        
    all_videos = [f for f in os.listdir(VIDEO_FOLDER) if f.lower().endswith(('.mp4', '.mov', '.mkv'))]
    sent_filenames = [entry['filename'] for entry in history]
    
    available_videos = [v for v in all_videos if v not in sent_filenames]
    
    if not available_videos:
        print("No new videos to send.")
        return

    video_to_send = random.choice(available_videos)
    video_path = os.path.join(VIDEO_FOLDER, video_to_send)
    
    print(f"Selected Video File: {video_to_send}")

    # 3. RANDOM SELECTION (Grid System)
    selected_title = random.choice(TITLES_GRID)
    selected_caption = random.choice(CAPTIONS_GRID)
    
    # Combine content
    full_telegram_caption = f"{selected_title}\n\n{selected_caption}\n{FIXED_HASHTAGS}"
    
    print(f"Generated Title: {selected_title}")
    print(f"Generated Caption: {selected_caption}")

    # 4. SEND TO TELEGRAM
    if TELEGRAM_BOT_TOKEN and TELEGRAM_CHAT_ID:
        print("Sending to Telegram...")
        with open(video_path, 'rb') as video_file:
            url = f"https://api.telegram.org/bot{TELEGRAM_BOT_TOKEN}/sendVideo"
            payload = {
                'chat_id': TELEGRAM_CHAT_ID, 
                'caption': full_telegram_caption
            }
            files = {'video': video_file}
            try:
                requests.post(url, data=payload, files=files)
            except Exception as e:
                print(f"Telegram Error: {e}")

    # 5. SEND TO WEBHOOK
    if WEBHOOK_URL:
        print("Sending to Webhook...")
        # URL construction with your specific repo name
        raw_video_url = f"https://raw.githubusercontent.com/{GITHUB_REPO}/{BRANCH_NAME}/{VIDEO_FOLDER}/{video_to_send}"
        # Encode spaces if any
        raw_video_url = raw_video_url.replace(" ", "%20")
        
        webhook_data = {
            "video_url": raw_video_url,
            "title": selected_title,
            "caption": selected_caption,
            "hashtags": FIXED_HASHTAGS,
            "insta_hashtags": INSTA_HASHTAGS, # Make.com mein isi naam se field aayegi
            "source": "AffiliateBot"
        }
        try:
            requests.post(WEBHOOK_URL, json=webhook_data)
            print(f"Webhook Sent: {raw_video_url}")
        except Exception as e:
            print(f"Webhook Error: {e}")

    # 6. UPDATE HISTORY
    new_history.append({
        "filename": video_to_send,
        "date_sent": today.isoformat()
    })
    save_history(new_history)
    print("Automation Complete.")

if __name__ == "__main__":
    run_automation()
